[package]
name = "humpties-generator"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny-skia = "0.6.3"
rand = "*"
rand_chacha = "*"